name: Deploy to DCL PROD

on:
  pull_request:
    types:
      - closed
    branches:
      - 'deploy'

env:
  DCL_PRIVATE_KEY: ${{ secrets.DCL_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dcl-scene

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install npm packages
      run: npm install

    - name: Build scene
      run: npm run build

    - name: Deploy scene
      run: npm run deploy
